### ISSUE TITLE
QuickStart consumer demo Request error 400

### ISSUE THREAD

**Issue by atomzhong** [polarismesh/grpc-java-polaris#20]

**Comment by atomzhong** [comment]
![image](https://user-images.githubusercontent.com/48663740/147524604-c6847f82-22b4-432d-9a91-2b8f03f34281.png)

![image](https://user-images.githubusercontent.com/48663740/147524570-c507ea0a-1e00-4e98-a402-c4c92607f24b.png)

**Comment by li-xiao-shuang** [comment]
稍等 我一会试一下

**Comment by li-xiao-shuang** [comment]
curl  命令去掉双引号"
