### ISSUE TITLE
com.tencent.polaris.specification 包不存在

### ISSUE THREAD

**Issue by wang007** [polarismesh/grpc-java-polaris#34]
![企业微信截图_36dda5fa-833f-4cbf-a53c-c1a0a87765e7](https://user-images.githubusercontent.com/15957476/222085309-842e58bf-91b4-4a96-9c31-cc6d1c6f05b7.png)

**Comment by chuntaojun** [comment]
本地自己 mvn clean install 即可，触发 pb 文件编译为 java
