### ISSUE TITLE
Examples optimize options

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/grpc-java-polaris#8]
1. split provider and consumer into 2 separated projects
2. provide executable fat jar build command for examples

**Comment by li-xiao-shuang** [comment]
1.  provider and consumer  Split two Modules?
2. Modify Examples packaging mode?

**Comment by li-xiao-shuang** [comment]
> 1. split provider and consumer into 2 separated projects
> 2. provide executable fat jar build command for examples

1.provider and consumer Split two Modules?
2.Modify Examples packaging mode?

**Comment by andrewshan** [comment]
> > 1. split provider and consumer into 2 separated projects
> > 2. provide executable fat jar build command for examples
> 
> 1.provider and consumer Split two Modules? 2.Modify Examples packaging mode?

1. yes, split into 2 modules to make in more convenience to deploy
2. make the 2 modules to package into executable main jar

**Comment by li-xiao-shuang** [comment]
> 

ok
